
name: Renovate

on:
  workflow_dispatch: {}
  # Regular schedule (every day at 03:00 UTC)
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: read
  pull-requests: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Run Renovate
        uses: renovatebot/github-action@822441559e94f98b67b82d97ab89fe3003b0a247 # v44.2.0
        env:
          LOG_LEVEL: info
          RENOVATE_REPOSITORIES: TOPdesk/vue-a11y-live-regions
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
